name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Build with Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        workdir: .
        buildozer_version: master

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Capuchinator-APK
        path: ${{ steps.buildozer.outputs.filename }}
