name: Build Android APK
on: 
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Buildozer dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libssl-dev libffi-dev liblzma-dev build-essential libsqlite3-dev
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build with Buildozer
      run: |
        yes y | buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Capuchinator-APK
        path: bin/*.apk
